// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ninebot_zmq/encoder.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ninebot_5fzmq_2fencoder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ninebot_5fzmq_2fencoder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ninebot_zmq/sensor_common.pb.h"
#include "ninebot_zmq/pose.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ninebot_5fzmq_2fencoder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ninebot_5fzmq_2fencoder_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ninebot_5fzmq_2fencoder_2eproto;
namespace Segway_proto {
class EncoderData;
class EncoderDataDefaultTypeInternal;
extern EncoderDataDefaultTypeInternal _EncoderData_default_instance_;
class StampedEncoderData;
class StampedEncoderDataDefaultTypeInternal;
extern StampedEncoderDataDefaultTypeInternal _StampedEncoderData_default_instance_;
}  // namespace Segway_proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Segway_proto::EncoderData* Arena::CreateMaybeMessage<::Segway_proto::EncoderData>(Arena*);
template<> ::Segway_proto::StampedEncoderData* Arena::CreateMaybeMessage<::Segway_proto::StampedEncoderData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Segway_proto {

// ===================================================================

class EncoderData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Segway_proto.EncoderData) */ {
 public:
  EncoderData();
  virtual ~EncoderData();

  EncoderData(const EncoderData& from);
  EncoderData(EncoderData&& from) noexcept
    : EncoderData() {
    *this = ::std::move(from);
  }

  inline EncoderData& operator=(const EncoderData& from) {
    CopyFrom(from);
    return *this;
  }
  inline EncoderData& operator=(EncoderData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EncoderData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EncoderData* internal_default_instance() {
    return reinterpret_cast<const EncoderData*>(
               &_EncoderData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(EncoderData* other);
  friend void swap(EncoderData& a, EncoderData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EncoderData* New() const final {
    return CreateMaybeMessage<EncoderData>(nullptr);
  }

  EncoderData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EncoderData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EncoderData& from);
  void MergeFrom(const EncoderData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EncoderData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Segway_proto.EncoderData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ninebot_5fzmq_2fencoder_2eproto);
    return ::descriptor_table_ninebot_5fzmq_2fencoder_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Segway_proto.Pose2Dd pose = 1;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 1;
  const ::Segway_proto::Pose2Dd& pose() const;
  ::Segway_proto::Pose2Dd* release_pose();
  ::Segway_proto::Pose2Dd* mutable_pose();
  void set_allocated_pose(::Segway_proto::Pose2Dd* pose);

  // double linear_velocity = 2;
  void clear_linear_velocity();
  static const int kLinearVelocityFieldNumber = 2;
  double linear_velocity() const;
  void set_linear_velocity(double value);

  // double angular_velocity = 3;
  void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 3;
  double angular_velocity() const;
  void set_angular_velocity(double value);

  // int32 left_ticks = 4;
  void clear_left_ticks();
  static const int kLeftTicksFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int32 left_ticks() const;
  void set_left_ticks(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 right_ticks = 5;
  void clear_right_ticks();
  static const int kRightTicksFieldNumber = 5;
  ::PROTOBUF_NAMESPACE_ID::int32 right_ticks() const;
  void set_right_ticks(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:Segway_proto.EncoderData)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::Segway_proto::Pose2Dd* pose_;
  double linear_velocity_;
  double angular_velocity_;
  ::PROTOBUF_NAMESPACE_ID::int32 left_ticks_;
  ::PROTOBUF_NAMESPACE_ID::int32 right_ticks_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ninebot_5fzmq_2fencoder_2eproto;
};
// -------------------------------------------------------------------

class StampedEncoderData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Segway_proto.StampedEncoderData) */ {
 public:
  StampedEncoderData();
  virtual ~StampedEncoderData();

  StampedEncoderData(const StampedEncoderData& from);
  StampedEncoderData(StampedEncoderData&& from) noexcept
    : StampedEncoderData() {
    *this = ::std::move(from);
  }

  inline StampedEncoderData& operator=(const StampedEncoderData& from) {
    CopyFrom(from);
    return *this;
  }
  inline StampedEncoderData& operator=(StampedEncoderData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StampedEncoderData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StampedEncoderData* internal_default_instance() {
    return reinterpret_cast<const StampedEncoderData*>(
               &_StampedEncoderData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(StampedEncoderData* other);
  friend void swap(StampedEncoderData& a, StampedEncoderData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StampedEncoderData* New() const final {
    return CreateMaybeMessage<StampedEncoderData>(nullptr);
  }

  StampedEncoderData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StampedEncoderData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StampedEncoderData& from);
  void MergeFrom(const StampedEncoderData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StampedEncoderData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Segway_proto.StampedEncoderData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ninebot_5fzmq_2fencoder_2eproto);
    return ::descriptor_table_ninebot_5fzmq_2fencoder_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Segway_proto.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::Segway_proto::Header& header() const;
  ::Segway_proto::Header* release_header();
  ::Segway_proto::Header* mutable_header();
  void set_allocated_header(::Segway_proto::Header* header);

  // .Segway_proto.EncoderData data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::Segway_proto::EncoderData& data() const;
  ::Segway_proto::EncoderData* release_data();
  ::Segway_proto::EncoderData* mutable_data();
  void set_allocated_data(::Segway_proto::EncoderData* data);

  // @@protoc_insertion_point(class_scope:Segway_proto.StampedEncoderData)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::Segway_proto::Header* header_;
  ::Segway_proto::EncoderData* data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ninebot_5fzmq_2fencoder_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EncoderData

// .Segway_proto.Pose2Dd pose = 1;
inline bool EncoderData::has_pose() const {
  return this != internal_default_instance() && pose_ != nullptr;
}
inline const ::Segway_proto::Pose2Dd& EncoderData::pose() const {
  const ::Segway_proto::Pose2Dd* p = pose_;
  // @@protoc_insertion_point(field_get:Segway_proto.EncoderData.pose)
  return p != nullptr ? *p : *reinterpret_cast<const ::Segway_proto::Pose2Dd*>(
      &::Segway_proto::_Pose2Dd_default_instance_);
}
inline ::Segway_proto::Pose2Dd* EncoderData::release_pose() {
  // @@protoc_insertion_point(field_release:Segway_proto.EncoderData.pose)
  
  ::Segway_proto::Pose2Dd* temp = pose_;
  pose_ = nullptr;
  return temp;
}
inline ::Segway_proto::Pose2Dd* EncoderData::mutable_pose() {
  
  if (pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::Segway_proto::Pose2Dd>(GetArenaNoVirtual());
    pose_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Segway_proto.EncoderData.pose)
  return pose_;
}
inline void EncoderData::set_allocated_pose(::Segway_proto::Pose2Dd* pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose_);
  }
  if (pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:Segway_proto.EncoderData.pose)
}

// double linear_velocity = 2;
inline void EncoderData::clear_linear_velocity() {
  linear_velocity_ = 0;
}
inline double EncoderData::linear_velocity() const {
  // @@protoc_insertion_point(field_get:Segway_proto.EncoderData.linear_velocity)
  return linear_velocity_;
}
inline void EncoderData::set_linear_velocity(double value) {
  
  linear_velocity_ = value;
  // @@protoc_insertion_point(field_set:Segway_proto.EncoderData.linear_velocity)
}

// double angular_velocity = 3;
inline void EncoderData::clear_angular_velocity() {
  angular_velocity_ = 0;
}
inline double EncoderData::angular_velocity() const {
  // @@protoc_insertion_point(field_get:Segway_proto.EncoderData.angular_velocity)
  return angular_velocity_;
}
inline void EncoderData::set_angular_velocity(double value) {
  
  angular_velocity_ = value;
  // @@protoc_insertion_point(field_set:Segway_proto.EncoderData.angular_velocity)
}

// int32 left_ticks = 4;
inline void EncoderData::clear_left_ticks() {
  left_ticks_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EncoderData::left_ticks() const {
  // @@protoc_insertion_point(field_get:Segway_proto.EncoderData.left_ticks)
  return left_ticks_;
}
inline void EncoderData::set_left_ticks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  left_ticks_ = value;
  // @@protoc_insertion_point(field_set:Segway_proto.EncoderData.left_ticks)
}

// int32 right_ticks = 5;
inline void EncoderData::clear_right_ticks() {
  right_ticks_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EncoderData::right_ticks() const {
  // @@protoc_insertion_point(field_get:Segway_proto.EncoderData.right_ticks)
  return right_ticks_;
}
inline void EncoderData::set_right_ticks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  right_ticks_ = value;
  // @@protoc_insertion_point(field_set:Segway_proto.EncoderData.right_ticks)
}

// -------------------------------------------------------------------

// StampedEncoderData

// .Segway_proto.Header header = 1;
inline bool StampedEncoderData::has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline const ::Segway_proto::Header& StampedEncoderData::header() const {
  const ::Segway_proto::Header* p = header_;
  // @@protoc_insertion_point(field_get:Segway_proto.StampedEncoderData.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::Segway_proto::Header*>(
      &::Segway_proto::_Header_default_instance_);
}
inline ::Segway_proto::Header* StampedEncoderData::release_header() {
  // @@protoc_insertion_point(field_release:Segway_proto.StampedEncoderData.header)
  
  ::Segway_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::Segway_proto::Header* StampedEncoderData::mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::Segway_proto::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Segway_proto.StampedEncoderData.header)
  return header_;
}
inline void StampedEncoderData::set_allocated_header(::Segway_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:Segway_proto.StampedEncoderData.header)
}

// .Segway_proto.EncoderData data = 2;
inline bool StampedEncoderData::has_data() const {
  return this != internal_default_instance() && data_ != nullptr;
}
inline void StampedEncoderData::clear_data() {
  if (GetArenaNoVirtual() == nullptr && data_ != nullptr) {
    delete data_;
  }
  data_ = nullptr;
}
inline const ::Segway_proto::EncoderData& StampedEncoderData::data() const {
  const ::Segway_proto::EncoderData* p = data_;
  // @@protoc_insertion_point(field_get:Segway_proto.StampedEncoderData.data)
  return p != nullptr ? *p : *reinterpret_cast<const ::Segway_proto::EncoderData*>(
      &::Segway_proto::_EncoderData_default_instance_);
}
inline ::Segway_proto::EncoderData* StampedEncoderData::release_data() {
  // @@protoc_insertion_point(field_release:Segway_proto.StampedEncoderData.data)
  
  ::Segway_proto::EncoderData* temp = data_;
  data_ = nullptr;
  return temp;
}
inline ::Segway_proto::EncoderData* StampedEncoderData::mutable_data() {
  
  if (data_ == nullptr) {
    auto* p = CreateMaybeMessage<::Segway_proto::EncoderData>(GetArenaNoVirtual());
    data_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Segway_proto.StampedEncoderData.data)
  return data_;
}
inline void StampedEncoderData::set_allocated_data(::Segway_proto::EncoderData* data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete data_;
  }
  if (data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    
  } else {
    
  }
  data_ = data;
  // @@protoc_insertion_point(field_set_allocated:Segway_proto.StampedEncoderData.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Segway_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ninebot_5fzmq_2fencoder_2eproto
